repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.241
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: add-spdx-headers
        name: Add SPDX headers to all Python files
        entry: python src/zilant_prime_core/scripts/add_spdx_headers.py src tests
        language: system
        files: \.py$
        stages: [commit]
