[project]
name = "zilant-prime-core"
version = "0.1.0"
description = "Core engine for ZILANT Prime™"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name = "QuantumKeyUYU", email = "you@example.com" }
]
requires-python = ">=3.9"
dependencies = [
  "cryptography>=41.0.0",
  "numpy>=1.25.0",
  "scipy>=1.11.0",
]

[project.optional-dependencies]
dev = [
  "pytest>=7.0",
  "flake8>=6.0",
  "bandit>=1.7",
  "mypy>=1.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
