[project]
name = "zilant-prime-core"
version = "0.1.0"
description = "Core engine for ZILANT Prime™"
readme = "README.md"
requires-python = ">=3.9"

# Авторы — PEP 621 требует массив таблиц
authors = [
  { name = "QuantumKeyUYU", email = "example@example.com" }
]

# Зависимости — PEP 621 требует массив строк в PEP 508 формате
dependencies = [
  "cryptography>=41.0.0",
  "numpy>=1.25.0",
  "scipy>=1.11.0",
]

[project.urls]
"Homepage" = "https://github.com/QuantumKeyUYU/zilant-prime-core"
"Repository" = "https://github.com/QuantumKeyUYU/zilant-prime-core"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
