[project]
name = "zilant-prime-core"
version = "0.1.0"
description = "Zilant Prime Core"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }

authors = [
  { name = "QuantumKeyUYU", email = "email@example.com" }
]

[project.urls]
Homepage   = "https://github.com/QuantumKeyUYU/zilant-prime-core"
Repository = "https://github.com/QuantumKeyUYU/zilant-prime-core"

[project.dependencies]
cryptography = "^41.0.0"
numpy         = "^1.25.0"
scipy         = "^1.11.0"

[project.optional-dependencies]
dev = [
  "pytest",
  "hypothesis",
  "black",
  "flake8",
  "mypy",
  "bandit"
]

[build-system]
requires    = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
license-files = ["LICENSE"]
