[project]
name = "zilant-prime-core"
version = "0.1.0"
description = "Zilant Prime Core"
authors = ["QuantumKeyUYU <email@example.com>"]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/QuantumKeyUYU/zilant-prime-core"
Repository = "https://github.com/QuantumKeyUYU/zilant-prime-core"

[project.optional-dependencies]
dev = ["pytest", "hypothesis", "black", "flake8", "mypy", "bandit"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
