[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zilant-prime-core"
version = "0.1.4"               # <-- не забыть обновить сюда вашу новую версию
description = "Core engine for ZILANT Prime™"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "QuantumKeyUYU" }]
keywords = ["crypto", "vdf", "aead", "kdf"]
dependencies = [
  "cryptography>=42,<43",
  "argon2-cffi>=23.1,<24",
  "click>=8.1,<9",
]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
]

[project.urls]
"Homepage" = "https://github.com/QuantumKeyUYU/zilant-prime-core"
