[build-system]
requires = ["setuptools>=60.0", "wheel"]

[project]
name = "zilant-prime-core"
version = "0.1.0"
description = "Core engine for ZILANT Prime™"
authors = [{name = "QuantumKeyUYU", email = "quantumkey@uyu.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
keywords = ["cryptography", "quantum", "security"]
dependencies = [
    "cryptography>=41.0.0",
    "numpy>=1.25.0",
    "scipy>=1.11.0"
]

[tool.flake8]
max-line-length = 88
exclude = .git,__pycache__,build,dist

[tool.bandit]
targets = ["src"]

[tool.mypy]
files = "src"
