[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zilant-prime-core"
version = "0.1.4"
description = "Core engine for Zilant Prime™"
authors = [{name = "QuantumKeyUYU"}]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10"

# ── основные зависимости ───────────────────────────────────────────
dependencies = [
    "click>=8.0",
    "cryptography>=42.0.0",
    # тесты (нужны раннеру)
    "pytest>=7.4",
    "pytest-cov>=4.1",
]

# ── «dev»‑пакет: всё, что нужно локально, но не на проде ────────────
[project.optional-dependencies]
dev = [
    "pytest>=7.4",
    "pytest-cov>=4.1",
    "hypothesis>=6.99",
    "black>=24.4",
    "ruff>=0.4",
    "build>=1.2",
]

[tool.setuptools.packages.find]
where = ["src"]

# ── pytest.ini лежит в корне, поэтому path не нужен ────────────────
#   (если хотите, можно перенести его в [tool.pytest.ini_options])

