[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zilant-prime-core"
version = "0.1.0"
description = "Core library for ZILANT Prime phase VDF and encryption"
readme = "README.md"
requires-python = ">=3.9,<4.0"    # <-- СЂР°СЃС€РёСЂРёР»Рё РґРѕ <4.0
license = { file = "LICENSE" }
authors = [
  { name = "Your Name", email = "you@example.com" },
]
dependencies = [
  "aead>=0.2,<1.0",
  "cryptography>=3.4.7",
  "argon2-cffi>=21.3.0",
  "hypothesis>=6.0.0",
]

[project.optional-dependencies]
dev = [
  "pytest>=7.0.0",
  "flake8>=5.0.0",
  "bandit>=1.7.0",
  "pre-commit>=2.20.0",
  "isort>=5.0",
  "black>=23.0",
]

[project.scripts]
bench-vdf = "bench_vdf:main"
