[project]
name = "zilant-prime-core"
version = "0.1.0"
description = "Core engine for ZILANT Prime"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "QuantumKeyUYU", email = "your-email@example.com" }
]
dependencies = [
    "cryptography>=40.0.0",
    "numpy>=1.25.0",
    "scipy>=1.11.0"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "flake8",
    "bandit",
    "mypy",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
