[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zilant-prime-core"
version = "0.1.0"
description = "Core engine for ZILANT Prime™"
readme = "README.md"
license = { text = "MIT" }
license-files = ["LICENSE"]
authors = [
  { name = "QuantumKeyUYU", email = "email@example.com" }
]
dependencies = [
  "cryptography>=41.0.0",
  "numpy>=1.25.0",
  "scipy>=1.11.0",
]

[project.urls]
homepage   = "https://github.com/QuantumKeyUYU/zilant-prime-core"
repository = "https://github.com/QuantumKeyUYU/zilant-prime-core"
