[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zilant-prime-core"
version = "0.1.4"
description = "Core primitives for Zilant Prime: AEAD, KDF, VDF and CLI tools"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

authors = [
  { name = "QuantumKeyUYU", email = "your.email@example.com" }
]

dependencies = [
  "click>=8.0",
  "cryptography>=36.0.0",
  "pytest>=7.0"          # ← вот эта строка
]

keywords = ["cryptography", "vdf", "kdf", "aead", "zilant"]

classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "License :: OSI Approved :: MIT License"
]

[project.urls]
"Homepage"   = "https://github.com/QuantumKeyUYU/zilant-prime-core"
"Repository" = "https://github.com/QuantumKeyUYU/zilant-prime-core"
