[project]
name = "zilant-prime-core"
version = "0.1.0"
description = "ZILANT Prime Core Library"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "QuantumKeyUYU", email = "example@email.com" }]
dependencies = [
    "cryptography",
    "setuptools",
    "wheel"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "flake8",
    "bandit",
    "mypy",
    "black"
]

[project.license-files]
include = ["LICENSE"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
