[project]
name = "zilant-prime-core"
version = "0.1.0"
description = "ZILANT Prime Core: cryptographic primitives for the ZILANT protocol"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name = "QuantumKeyUYU", email = "you@example.com" }]
keywords = ["zilant","cryptography","vdf","prime","kdf"]

dependencies = [
  "aead>=0.2,<1.0",
  "cryptography>=3.4.7",
  "argon2-cffi>=21.3.0",
  "hypothesis>=6.0.0",
]

[project.optional-dependencies]
dev = [
  "pytest>=7.0.0",
  "flake8>=5.0.0",
  "bandit>=1.7.0",
  "pre-commit>=2.20.0",
  "isort>=5.0",
  "black>=23.0",
]

[build-system]
requires = ["setuptools>=42","wheel"]
build-backend = "setuptools.build_meta"
