[project]
name = "zilant-prime-core"
version = "0.1.0"
description = "Zilant Prime Core engine"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "QuantumKeyUYU", email = "quantumkey@uyu.com" }
]

dependencies = [
  "cryptography>=41.0.0",
  "numpy>=1.25.0",
  "scipy>=1.11.0"
]

[project.optional-dependencies]
dev = [
  "pytest>=7.0",
  "flake8>=6.0",
  "mypy>=1.0",
  "bandit>=1.7"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
