[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name            = "zilant-prime-core"
version         = "0.1.4"
description     = "Core engine for Zilant Prime™"
authors         = [{ name = "QuantumKeyUYU" }]
readme          = "README.md"
license         = { text = "MIT" }
requires-python = ">=3.10"

dependencies = [
  "click>=8.0",
  "cryptography>=42.0.0",
  "argon2-cffi>=21.3",
]

[project.optional-dependencies]
dev = [
  "pytest>=7.4",
  "pytest-cov>=4.1",
  "hypothesis>=6.99",
  "black>=24.4",
  "ruff>=0.4",
  "build>=1.2",
]

[project.scripts]
zilant = "zilant_prime_core.cli:main"

[project.urls]
Homepage  = "https://github.com/QuantumKeyUYU/zilant-prime-core"
Source    = "https://github.com/QuantumKeyUYU/zilant-prime-core"
Issues    = "https://github.com/QuantumKeyUYU/zilant-prime-core/issues"
Changelog = "https://github.com/QuantumKeyUYU/zilant-prime-core/releases"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts    = "-ra --cov=src --cov-report=term"
testpaths  = ["tests"]

[tool.coverage.run]
branch = true
omit   = ["*/tests/*", "*/.pytest_cache/*", "*/.ruff_cache/*"]

[tool.black]
line-length    = 100
target-version = ["py310"]

[tool.ruff]
line-length    = 100
target-version = "py310"
select         = ["E", "F", "I", "N", "B", "UP", "ARG"]
fixable        = ["ALL"]
src            = ["src", "tests"]
exclude        = [
  ".git",
  ".venv",
  ".mypy_cache",
  ".pytest_cache",
  "build",
  "dist",
]
extend-ignore  = ["E203"]

[tool.hypothesis]
deadline = 1000
