line-length = 100
target-version = "py310"

[lint]
select = ["E", "F", "I", "N", "B"]
ignore = ["I001", "B904", "N802"]

[lint.per-file-ignores]
"tests/**/*.py" = [
  "F401",
  "F841",
  "I001",
  "E501",
  "E702",
  "B904"
]
