# ruff.toml — плоская конфигурация для Ruff

# длина строки и версия Python
line-length = 100
target-version = "py310"

# какие категории проверять
select = ["E", "F", "I", "N", "B"]

# индивидуальные игнор-правила для файлов
[per-file-ignores]
"tests/*.py" = ["F401"]
