# ruff.toml — конфигурация для Ruff 0.4+

line-length    = 100
target-version = "py310"

[lint]
select = ["E", "F", "I", "N", "B"]
ignore = [
  "I001",  # порядок импортов (доверяем isort/ruff-isort)
  "B904",  # recommends raise … from
  "N802",  # snake_case для функций
]

[lint.per-file-ignores]
"tests/**/*.py" = [
  "F401",  # неиспользуемый import
  "F841",  # неиспользуемая переменная
  "I001",  # порядок импортов
  "E501",  # длина строки
  "E702",  # несколько stmts на строке
  "B904",  # raise-from
]
