# .ruff.toml

[tool.ruff]
# Максимальная длина строки, версия Python
line-length = 100
target-version = "py310"

# ─── Основные правила ───────────────────────────────────
[tool.ruff.lint]
# Какие категории ошибок мы хотим ловить
select = ["E", "F", "I", "N", "B"]
# (не обязательно фиксабельные – отключаем только в тестах)

# ─── Исключения для тестов ───────────────────────────────
[tool.ruff.per-file-ignores]
# во всех файлах tests/*.py не считать ошибкой «unused import»
"tests/*.py" = ["F401"]
