# ruff.toml

# Выбираем правила, которые хотим проверять и автоматически исправлять
select = ["F401", "E402", "E261", "E262"]

# Разрешаем фиксить именно эти
fixable = ["F401", "E402", "E261", "E262"]
