# ruff.toml — конфигурация для Ruff ≥ 0.4

line-length    = 100
target-version = "py310"

[lint]
select = ["E", "F", "I", "N", "B"]
ignore = [
  "I001",  # порядок импортов
  "B904",  # raise-from
  "N802",  # snake_case функций
]

[lint.per-file-ignores]
"tests/**/*.py" = [
  "F401",  # unused import
  "F841",  # unused variable
  "I001",  # порядок импортов
  "E501",  # длина строки
  "E702",  # несколько stmt в строке
  "B904",
]
