# минимальный stub-файл: только упомянутые в коде классы
from typing import Any

class QApplication: ...
class QMenu: ...

class QSystemTrayIcon:
    def __init__(self, *args: Any, **kw: Any) -> None: ...
    def show(self) -> None: ...
    def setContextMenu(self, m: QMenu) -> None: ...

class QAction:
    def __init__(self, text: str) -> None: ...

    class _Signal:
        def connect(self, *__a: Any, **__kw: Any) -> None: ...

    triggered: _Signal
