name: VDF Benchmark

# Запускаем по расписанию и вручную
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # каждый день в UTC 00:00

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install package
        run: pip install -e .

      - name: Run VDF benchmark
        run: python bench_vdf.py --size 200 --steps 5000 --lam 0.3 --runs 10 > results.txt

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: vdf-benchmark
          path: results.txt
