name: Build & Test

on:
  push:
    branches:
      - main
      - fix/ci-no-build-isolation
  pull_request:
    branches:
      - main
      - fix/ci-no-build-isolation

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dev dependencies
        run: pip install -e .[dev] --no-build-isolation

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
