jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for BOM
        run: |
          echo "Ищем BOM в .py/.md/.toml..."
          grep -rI --include="*.py" --include="*.md" --include="*.toml" $'\xEF\xBB\xBF' . || true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -e .[dev]
