      - name: Detect BOM/UTF-16 signatures
        run: |
          echo "┌── Проверяем все .py, .md и .toml файлы на наличие BOM/UTF-16"
          
          # Ищем все потенциально проблемные файлы
          find . -type f \( -name '*.py' -o -name '*.md' -o -name '*.toml' \) | while read f; do
            # Проверяем первые 3 байта
            sig=$(head -c3 "$f" | xxd -p -u)
            if [[ "$sig" == "efbbbf"* ]]; then
              echo "💥 BOM UTF-8   -> $f"
            elif [[ "$sig" == "fffe"* ]]; then
              echo "💥 BOM UTF-16LE-> $f"
            elif [[ "$sig" == "feff"* ]]; then
              echo "💥 BOM UTF-16BE-> $f"
            fi
          done || true
          
          echo "└── Проверка завершена"
