      - name: Detect BOM/UTF-16 signatures
        run: |
          echo "┌── Начинаем строгую проверку файлов на BOM/UTF-16"
          
          # Ищем все .py, .md и .toml файлы
          find . -type f \( -name '*.py' -o -name '*.md' -o -name '*.toml' \) | while read -r f; do
            # Считываем первые 3 байта
            sig=$(xxd -p -l 3 "$f" | tr '[:lower:]' '[:upper:]')
            
            # Проверяем сигнатуру BOM
            if [[ "$sig" == "EFBBBF"* ]]; then
              echo "💥 BOM UTF-8   -> $f"
              exit 1
            elif [[ "$sig" == "FEFF"* ]]; then
              echo "💥 BOM UTF-16BE -> $f"
              exit 1
            elif [[ "$sig" == "FFFE"* ]]; then
              echo "💥 BOM UTF-16LE -> $f"
              exit 1
            fi
          done
          
          echo "✔️ Все файлы чисты — ни одного BOM не найдено"
