name: Foundation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# нужно для выгрузки SARIF и Codecov
permissions:
  contents: read
  security-events: write

jobs:
  lint-format:
    name: Lint & Format (${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dev‑deps
        run: pip install -e .[dev]

      - name: Ruff
        run: ruff check src tests
      - name: Black
        run: black --check src tests
      - name: Isort
        run: isort --check-only src tests

  tests:
    name: Tests & Coverage (${{ matrix.python }})
    runs-on: ubuntu-latest
    needs: lint-format
    strategy:
      matrix:
        python: ["3.13"]          # 100 % тесты нам важны хоть на одной версии

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dev‑deps
        run: pip install -e .[dev]

      - name: Run pytest
        run: |
          pytest -q --cov=src/zilant_prime_core --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
