# .github/workflows/ci.yml
name: CI — lint / pytest / coverage / security & sign

permissions:
  actions: read
  contents: read
  security-events: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install black ruff isort

      - name: Black (check-only)
        run: black --check src tests

      - name: Ruff (check-only)
        run: ruff check src tests

      - name: isort (check-only)
        run: isort --check-only src tests

  pytest-coverage:
    needs: lint-format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install .

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings --quiet

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-xml-${{ matrix.python }}
          path: coverage.xml

      - uses: actions/upload-artifact@v4
        with:
          name: htmlcov-${{ matrix.python }}
          path: htmlcov

  security-and-sign:
    needs: pytest-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Syft / Grype / Trivy + Python tools
        run: |
          sudo apt-get update -y
          curl -sfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          curl -sfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          python -m pip install --upgrade pip
          pip install reuse bandit semgrep

      - name: Generate SBOM (Syft)
        run: syft . -o cyclonedx-json=sbom.json

      - name: Scan SBOM with Grype (fail on critical)
        run: grype sbom:sbom.json --fail-on critical

      - name: Save Grype report
        if: always()
        run: grype sbom:sbom.json -o json > grype-report.json

      - name: Scan SBOM with Trivy
        run: trivy sbom:sbom.json --format json --output trivy-report.json --severity HIGH,CRITICAL
        continue-on-error: true

      - name: REUSE lint
        run: reuse lint || true

      - name: Bandit
        run: bandit -r src -f json -o bandit-report.json || true

      - name: Semgrep
        run: semgrep --config p/ci --sarif-output=semgrep-report.sarif || true

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild CodeQL
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3

      - name: Write Cosign private key (Base64)
        env:
          COSIGN_KEY_B64: ${{ secrets.COSIGN_KEY_B64 }}
        run: |
          mkdir -p ~/.cosign
          echo "$COSIGN_KEY_B64" | base64 -d > ~/.cosign/cosign.key
          chmod 600 ~/.cosign/cosign.key

      - name: Install Cosign (Official binary)
        run: |
          COSIGN_VERSION="v2.2.4"
          curl -LO "https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64"
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign
          sudo chmod +x /usr/local/bin/cosign
          cosign version

      - name: Install build tool
        run: python -m pip install build

      - name: Build wheel & sdist
        run: python -m build --sdist --wheel --outdir dist

      - name: Sign artifacts with Cosign
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          for artifact in dist/*.{whl,tar.gz}; do
            cosign sign --key ~/.cosign/cosign.key "$artifact"
          done

      - uses: actions/upload-artifact@v4
        with:
          name: sbom-json
          path: sbom.json

      - uses: actions/upload-artifact@v4
        with:
          name: grype-report
          path: grype-report.json

      - uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json

      - uses: actions/upload-artifact@v4
        with:
          name: reuse-report
          path: .

      - uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json

      - uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.sarif

      - uses: actions/upload-artifact@v4
        with:
          name: signed-python-packages
          path: |
            dist/*.whl
            dist/*.tar.gz
            dist/*.whl.sig
            dist/*.tar.gz.sig
