name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: "3.10" }
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt pytest cryptography click
      - run: pytest --maxfail=1 --disable-warnings -q
