name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Scan for vulnerabilities
        run: python tools/vulnerability_scanner.py
      - name: Ruff lint
        run: ruff .
      - name: Black check
        run: black --check .
      - name: Run tests
        run: |
          pytest --cov=src --cov-report=xml
      - name: Verify coverage
        run: coverage report --fail-under=90
