name: ZILANT Prime CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    name: Build & Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Strip BOM (if any) via Python
        run: |
          python3 - <<'PYCODE'
          from pathlib import Path
          for f in Path('.').rglob('*'):
              if f.is_file():
                  data = f.read_bytes()
                  if data.startswith(b'\xef\xbb\xbf'):
                      f.write_bytes(data[3:])
          PYCODE

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip & build tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dev dependencies
        run: pip install --no-build-isolation -e .[dev]

      - name: Run tests
        run: pytest -q

      - name: Lint with flake8
        run: python -m flake8

      - name: Security scan with bandit
        run: bandit -r src -x tests -n 5
