name: CI — lint/pytest/coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install tooling
        run: pip install black ruff isort
      - name: Black (check-only)
        run: black --check src tests
      - name: Ruff (check-only)
        run: ruff check src tests
      - name: isort (check-only)
        run: isort --check-only src tests

  pytest-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install .
      - name: Run pytest with coverage
        run: |
          pytest
      - name: Upload coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml-${{ matrix.python-version }}
          path: coverage.xml
      - name: Upload coverage HTML (optional)
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov-${{ matrix.python-version }}
          path: htmlcov
