name: CI (Paranoid Stage 0)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_and_test:
    name: 🧪 Lint & Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (dev)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run pre-commit hooks
        run: pre-commit run --all-files || true

      - name: Run ruff (lint)
        run: ruff check src tests

      - name: Run black (format check)
        run: black --check src tests

      - name: Run isort (import order)
        run: isort --check-only src tests

      - name: Run mypy (type check)
        run: mypy src

      - name: Run pytest with coverage
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=src
          coverage xml -o coverage.xml
          coverage html -d htmlcov

      - name: ⬆️ Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            htmlcov/

  sbom_scan:
    name: SBOM ➔ Grype / Trivy
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: 🛠 Install Syft / Trivy / Grype (официальные скрипты)
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: ⚙️ Generate SBOM (CycloneDX JSON, исключаем .github)
        run: syft . -o cyclonedx-json=sbom.json --exclude .github

      - name: 🧪 Grype scan (fail-on medium)
        run: grype sbom:sbom.json --fail-on medium

      - name: 🔍 Scan filesystem with Trivy (High / Critical)
        run: trivy fs . --severity HIGH,CRITICAL --exit-code 0 --no-progress

      - name: ⬆️ Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
