# .github/workflows/ci.yml
name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Build & Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # Обратите внимание: не 3.1, а 3.10!
        python-version: [3.9, 3.10, 3.11]

    steps:
      # 1) Забираем код
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Ставим нужный Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # 3) Обновляем pip, setuptools & wheel
      - name: Upgrade pip, setuptools & wheel
        run: python -m pip install --upgrade pip setuptools wheel

      # 4) Устанавливаем проект вместе со всеми dev-зависимостями
      - name: Install dev dependencies
        run: pip install -e .[dev]

      # 5) Запускаем тесты
      - name: Run tests
        run: pytest -q

      # 6) Линтим код
      - name: Lint with flake8
        run: flake8

      # 7) Сканируем на уязвимости
      - name: Security scan with bandit
        run: bandit -r .
