# .github/workflows/ci.yml
name: CI (build wheel)

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: Strip BOM from pyproject.toml
        run: python strip_bom.py

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip, setuptools, wheel
        run: pip install --upgrade pip setuptools wheel

      - name: Build wheel
        run: python -m build --wheel --no-isolation .

      - name: Install wheel + dev dependencies
        run: |
          pip install dist/*.whl
          pip install pytest flake8 bandit

      - name: Run tests
        run: pytest -q

      - name: Lint with flake8
        run: flake8 .

      - name: Security scan with bandit
        run: bandit -r src
