name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: python-version: 3.11
      - run: pip install --upgrade pip setuptools wheel
      - run: python strip_bom.py pyproject.toml
      - run: pip install ".[dev]" --no-build-isolation
      - run: flake8 .

  security:
    name: Security scan with bandit
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: python-version: 3.11
      - run: pip install --upgrade pip setuptools wheel
      - run: pip install ".[dev]" --no-build-isolation
      - run: bandit -r src

  typecheck:
    name: Type-check with mypy
    runs-on: ubuntu-latest
    needs: security
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: python-version: 3.11
      - run: pip install --upgrade pip setuptools wheel
      - run: pip install ".[dev]" --no-build-isolation
      - run: mypy src
