name: Lint & Security Checks

on:
  push:
    branches:
      - main
      - fix/ci-no-build-isolation
  pull_request:
    branches:
      - main
      - fix/ci-no-build-isolation

jobs:
  lint-and-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dev dependencies
        run: pip install -e .[dev] --no-build-isolation

      - name: Run flake8
        run: flake8 .

      - name: Run bandit
        run: bandit -r src

      - name: Run mypy
        run: mypy src
