# .github/workflows/ci.yml
name: CI — lint / pytest / coverage / security & sign

###############################################################################
# базовые разрешения для job-ов
###############################################################################
permissions:
  contents:        read
  actions:         read
  security-events: write

###############################################################################
# триггеры
###############################################################################
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  #############################################################################
  # 1 — LINT / FORMAT
  #############################################################################
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip (linters)
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-lint-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install black ruff isort

      - name: Black (check-only)
        run: |
          black --check src tests

      - name: Ruff (check-only)
        run: |
          ruff check src tests

      - name: isort (check-only)
        run: |
          isort --check-only src tests

  #############################################################################
  # 2 — TESTS + COVERAGE (matrix 3.10–3.13)
  #############################################################################
  pytest-coverage:
    needs: lint-format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip (tests)
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install .

      - name: Run pytest
        run: |
          pytest -q

      - name: Upload coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: cov-xml-${{ matrix.python-version }}
          path: coverage.xml

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov-${{ matrix.python-version }}
          path: htmlcov

  #############################################################################
  # 3 — SECURITY SCANS + BUILD & SIGN
  #############################################################################
  security-and-sign:
    needs: pytest-coverage
    runs-on: ubuntu-latest
    env:
      COSIGN_KEY_B64:  ${{ secrets.COSIGN_KEY_B64 }}
      COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      #############################################################################
      # 3.1 — Установим Syft, Grype, Trivy и Python-утилиты
      #############################################################################
      - name: Install Syft / Grype / Trivy / python-helpers
        run: |
          sudo apt-get update -y

          # Syft (генерация SBOM)
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sudo sh -s -- -b /usr/local/bin

          # Grype (сканирование SBOM)
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh \
            | sudo sh -s -- -b /usr/local/bin

          # Trivy (дополнительный SBOM-скан)
          curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sudo sh -s -- -b /usr/local/bin

          python -m pip install --upgrade pip
          pip install reuse bandit semgrep build

      #############################################################################
      # 3.2 — Генерируем SBOM и сканируем на уязвимости
      #############################################################################
      - name: Generate SBOM (Syft → CycloneDX)
        run: |
          syft . -o cyclonedx-json=sbom.json

      - name: Grype scan (fail on CRITICAL)
        run: |
          grype sbom:sbom.json --fail-on critical

      - name: Save full Grype report (JSON)
        if: always()
        run: |
          grype sbom:sbom.json -o json > grype-report.json || true

      - name: Trivy scan (HIGH,CRITICAL)
        run: |
          trivy sbom \
            --scanners vuln \
            --severity HIGH,CRITICAL \
            --format json \
            --output trivy-report.json \
            sbom.json || true

      - name: Ensure trivy-report.json exists
        run: |
          if [ ! -f trivy-report.json ]; then
            echo "{}" > trivy-report.json
          fi

      #############################################################################
      # 3.3 — Static analysis + license check (REUSE, Bandit, Semgrep)
      #############################################################################
      - name: REUSE lint (license compliance)
        run: |
          reuse lint || true

      - name: Bandit (security linter)
        run: |
          bandit -r src -f json -o bandit-report.json || true

      - name: Semgrep (OSS rules)
        run: |
          semgrep --config p/ci --sarif-output semgrep.sarif || true

      #############################################################################
      # 3.4 — CodeQL analysis (init → autobuild → analyze)
      #############################################################################
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild CodeQL
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3

      #############################################################################
      # 3.5 — Подготовка Cosign-ключа (если есть)
      #############################################################################
      - name: Decode Cosign private key from Base64
        if: env.COSIGN_KEY_B64 != ''
        run: |
          mkdir -p ~/.cosign
          echo "$COSIGN_KEY_B64" | base64 -d > ~/.cosign/cosign.key
          chmod 600 ~/.cosign/cosign.key

      - name: Install Cosign
        if: env.COSIGN_KEY_B64 != ''
        run: |
          COSIGN_VERSION="v2.2.4"
          curl -LO https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64
          sudo install cosign-linux-amd64 /usr/local/bin/cosign
          cosign version

      #############################################################################
      # 3.6 — Сборка Python-пакета (wheel + sdist)
      #############################################################################
      - name: Build Python package
        run: |
          python -m build --sdist --wheel --outdir dist

      #############################################################################
      # 3.7 — Подпись дистрибутивов (если ключ есть)
      #############################################################################
      - name: Cosign sign artifacts
        if: env.COSIGN_KEY_B64 != ''
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          for f in dist/*.{whl,tar.gz}; do
            cosign sign --key ~/.cosign/cosign.key "$f"
          done

      #############################################################################
      # 3.8 — Загрузка всех полезных артефактов
      #############################################################################
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

      - name: Upload Grype report
        uses: actions/upload-artifact@v4
        with:
          name: grype-report
          path: grype-report.json

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json

      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json

      - name: Upload Semgrep SARIF
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.sarif

      - name: Upload signed packages
        uses: actions/upload-artifact@v4
        with:
          name: signed-packages
          path: |
            dist/*.whl
            dist/*.tar.gz
            dist/*.sig
