name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # убрал 3.1 и 3.12, оставил только поддерживаемые
        python-version: [ "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests
        run: pytest -q

  lint-and-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install lint tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit

      - name: Run flake8
        run: flake8 src --max-line-length=120 --extend-ignore=E203,W503

      - name: Run bandit
        run: bandit -r src
