name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        python: [3.10, 3.11, 3.12]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run tests and collect coverage
      run: pytest --cov=src --cov-report=xml --junitxml=results-${{ matrix.python }}.xml

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.python }}
        path: results-${{ matrix.python }}.xml

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-xml-${{ matrix.python }}
        path: coverage.xml
