name: Foundation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  lint-format:
    name: Lint & Format (${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dev‑deps
        run: pip install -e .[dev]

      - run: ruff check src tests
      - run: black --check src tests
      - run: isort --check-only src tests

  tests:
    name: Tests & Coverage (${{ matrix.python }})
    runs-on: ubuntu-latest
    needs: lint-format
    strategy:
      matrix:
        python: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dev‑deps + pytest‑cov
        run: |
          pip install -e .[dev]
          pip install pytest-cov              # гарантированно есть плагин

      - name: Run tests
        run: |
          coverage run -m pytest -q
          coverage xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
