# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip, setuptools, wheel
        run: pip install --upgrade pip setuptools wheel

      - name: Install package + dev dependencies
        run: |
          pip install .[dev]

      - name: Run tests
        run: pytest -q

      - name: Lint with flake8
        run: flake8 .

      - name: Security scan with bandit
        run: bandit -r src
