name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: read

jobs:
  lint-format:
    name: 🔍 Ruff / Black / MyPy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run linters
        run: |
          ruff check src tests
          black --check src tests
          mypy src

  tests:
    name: ✅ PyTest (matrix)
    needs: lint-format
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run tests + coverage
        run: |
          pytest -q --cov=src/zilant_prime_core --cov-report=xml --disable-warnings

      - name: Upload coverage XML
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
