# .github/workflows/cosign-sign-artifacts.yml
name: Sign Artifacts with Cosign

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

env:
  # COSIGN_PASSWORD подтянется из fetch-secrets → outputs или из GitHub Secrets напрямую:
  COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

jobs:
  build-and-sign:
    name: Build Python package and sign with Cosign
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build distribution packages
        run: |
          python -m build --sdist --wheel

      - name: Download Cosign (v2.0.1)
        run: |
          COSIGN_VERSION="v2.0.1"
          curl -LsS "https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64" \
            -o cosign
          chmod +x cosign
          sudo mv cosign /usr/local/bin/cosign

      - name: Sign each artifact in dist/
        run: |
          for artifact in dist/*; do
            cosign sign --key cosign.key --password-env COSIGN_PASSWORD "$artifact"
          done
