name: fuse

on:
  pull_request:
    paths:
      - 'src/zilant_prime_core/zilfs.py'
      - 'tests/test_zilfs*'
      - '.github/workflows/fuse.yml'

jobs:
  fuse-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install FUSE
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update -qq
            sudo apt-get install -y fuse3 libfuse3-dev
          else
            brew install macfuse fusepy
          fi
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install deps
        run: pip install -e .[dev,zilfs]
      - name: Run tests
        env:
          ZILANT_ALLOW_ROOT: '1'
        run: pytest -q -m zilfs
  windows-smoke:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Install WinFSP
        run: choco install winfsp -y
      - name: Add Path
        run: echo "C:\\Program Files\\WinFsp\\bin" >> $env:GITHUB_PATH
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install deps
        run: pip install -e .[zilfs]
      - name: Smoke import
        run: python -c "import zilant_prime_core.zilfs"
