# .github/workflows/lint-and-security.yml
name: Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-security:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Strip BOM (если есть)
        run: |
          sed -i '1s/^\xEF\xBB\xBF//' README.md

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install build tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dev deps
        run: pip install -e .[dev]

      - name: Run flake8
        run: python -m flake8

      - name: Security scan with bandit
        run: python -m bandit -r src
