name: lint-and-security

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-security:
    name: lint-and-security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dev-tools
        run: pip install -e .[dev]

      - name: Run flake8
        run: python -m flake8

      - name: Security scan with bandit
        run: bandit -r src -x tests -n 5
