name: Lint & Security Checks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-security:
    name: lint-and-security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Strip BOM (if any) via Python
        run: |
          python3 - <<'PYCODE'
          from pathlib import Path
          for f in Path('.').rglob('*'):
              if f.is_file():
                  data = f.read_bytes()
                  if data.startswith(b'\xef\xbb\xbf'):
                      f.write_bytes(data[3:])
          PYCODE

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dev-tools
        # no-build-isolation на случай, если снова будут проблемы с PEP 517
        run: pip install --no-build-isolation -e .[dev]

      - name: Lint with flake8
        run: python -m flake8

      - name: Security scan with bandit
        run: bandit -r src -x tests -n 5
