name: linux-fuse

on:
  pull_request:
    paths:
      - 'src/zilant_prime_core/zilfs.py'
      - 'tests/test_zilfs*'
      - '.github/workflows/linux-fuse.yml'

jobs:
  fuse-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install FUSE
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y fuse3 libfuse3-dev
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install deps
        run: pip install -e .[dev,zilfs]
      - name: Run tests
        env:
          ZILANT_ALLOW_ROOT: '1'
          FUSE_LIBRARY_PATH: /lib/x86_64-linux-gnu/libfuse3.so
        run: pytest -q -m zilfs
