name: Quality

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install .[metrics,notify] -r requirements-dev.txt
      - name: Pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
      - run: ruff check .
      - run: black --check .
      - run: isort --check-only .
      - run: bandit -r src -ll
      - name: Run Semgrep
        run: semgrep ci
