name: Publish

on:
  push:
    tags:
      - 'v*'          # срабатывает только на теги

permissions:
  contents: read
  id-token: write     # нужен для trusted‑publisher (если настроен)
  # OR packages: write  # если используем PyPI‑token

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Build dist
      run: |
        python -m pip install -U pip build
        python -m build

    - name: Publish to PyPI
      # ====== вариант 1 — Trusted Publisher ======
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # если репозиторий уже привязан к PyPI как «trusted publisher»
        skip-existing: true

      # ====== ИЛИ вариант 2 — старый PyPI‑token ======
      # uses: pypa/gh-action-pypi-publish@release/v1
      # with:
      #   password: ${{ secrets.PYPI_API_TOKEN }}
      #   skip-existing: true
