# .github/workflows/release.yml
name: Publish Release

on:
  push:
    # при пуше тега вида vX.Y.Z
    tags:
      - 'v*.*.*'

permissions:
  contents: write     # нужно для загрузки подписи в релиз
  packages: write     # нужно для пуша в PyPI

jobs:
  build-sign-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'       # например '3.12'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build

      - name: Build distributions
        run: python -m build

      - name: Sign distributions with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3
        with:
          # на события release подпишет все артефакты автоматически
          upload-signing-artifacts: true
        env:
          # сюда кладёте приватный ключ cosign без base64!
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
          # если ключ защищён паролем:
          # COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
