name: SBOM & CVE Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Build SBOM
        run: syft . -o cyclonedx-json=sbom.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

  scan-sbom:
    runs-on: ubuntu-latest
    needs: generate-sbom
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sbom
      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
      - name: CVE scan
        run: grype sbom:sbom.json --fail-on medium
