# .github/workflows/sbom-cve.yml
name: SBOM & CVE Scan

on:
  push:        { branches: ["main"] }
  pull_request:{ branches: ["main"] }

permissions:
  contents: read
  security-events: write

jobs:
  generate-sbom-and-scan:
    runs-on: ubuntu-latest
    name: Generate SBOM and scan for vulnerabilities

    steps:
      # 1. Код
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Trivy
      - name: Ensure Trivy is installed
        run: |
          if ! command -v trivy &> /dev/null; then
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
              | sudo bash -s -- -b /usr/local/bin v0.61.1
          fi

      # 3. Syft
      - name: Ensure Syft is installed
        run: |
          if ! command -v syft &> /dev/null; then
            curl -sfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
              | sh -s -- -b /usr/local/bin v0.84.0
          fi

      # 4. Генерируем SBOM в CycloneDX‑JSON
      - name: Generate SBOM (CycloneDX JSON)
        run: syft dir:. --output cyclonedx-json > sbom.json

      # 5. Грузим SBOM
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4      # ← обновили
        with:
          name: sbom-json
          path: sbom.json

      # 6. Сканируем SBOM Trivy’ем
      - name: Scan SBOM with Trivy
        run: trivy sbom --input sbom.json --format json --output trivy-report.json

      # 7. Грузим отчёт Trivy
      - name: Upload Trivy report
        uses: actions/upload-artifact@v4      # ← обновили
        with:
          name: trivy-sbom-report
          path: trivy-report.json
