# .github/workflows/sbom-cve.yml

name: "SBOM & CVE Scan (Syft + Trivy)"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  generate-sbom-and-scan:
    name: "Generate SBOM and scan for vulnerabilities"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Syft (SBOM generator)
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin v0.104.0

      - name: Generate SBOM (CycloneDX JSON)
        run: |
          syft . --output cyclonedx-json=sbom.json

      - name: Upload SBOM (CycloneDX JSON)
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx-json
          path: sbom.json

      - name: Install Trivy (CVE scanner)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.51.1

      - name: Scan SBOM with Trivy (CVE/License)
        run: |
          trivy sbom sbom.json --format json --output trivy-sbom-report.json

      - name: Upload Trivy SBOM scan report (JSON)
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: trivy-sbom-report.json
