# .github/workflows/sbom-cve.yml
name: SBOM & CVE Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  sbom-cve-scan:
    name: Generate SBOM and scan for vulnerabilities
    runs-on: ubuntu-latest

    steps:
      # 1) Чекаутим репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Устанавливаем Trivy через официальный Action
      - name: Install Trivy
        uses: aquasecurity/trivy-action@master

      # 3) Генерируем SBOM в формате CycloneDX-JSON
      - name: Generate SBOM (CycloneDX-JSON)
        run: |
          trivy sbom --format cyclonedx --output sbom.json .

      # 4) Сканируем получённый SBOM на уязвимости HIGH/CRITICAL
      - name: Scan SBOM for HIGH/CRITICAL vulnerabilities
        run: |
          trivy sbom --format table --scanners vuln --severity HIGH,CRITICAL sbom.json

      # 5) Загружаем sbom.json как артефакт (чтобы можно было скачать после выполнения)
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom-json
          path: sbom.json

      # 6) Генерируем JSON-отчёт (опционально) и тоже загружаем
      - name: Generate Trivy JSON report
        if: always()
        run: |
          trivy sbom --format json --scanners vuln --severity HIGH,CRITICAL sbom.json > trivy-report.json

      - name: Upload Trivy JSON report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report-json
          path: trivy-report.json
