# .github/workflows/sbom-cve.yml
name: SBOM & CVE Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  generate-sbom-and-scan:
    name: Generate SBOM and scan for vulnerabilities
    runs-on: ubuntu-latest

    steps:
      # 1) ЗАПУЛЛИТЬ КОД
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) УСТАНОВИТЬ Trivy, если его нет 
      - name: Ensure Trivy is installed
        run: |
          if ! command -v trivy &> /dev/null; then
            echo "Installing Trivy..."
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo bash -s -- -b /usr/local/bin v0.61.1
          fi

      # 3) УСТАНОВИТЬ Syft, если его нет
      - name: Ensure Syft is installed
        run: |
          if ! command -v syft &> /dev/null; then
            echo "Installing Syft..."
            curl -sfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin v0.84.0
          fi

      # 4) Сгенерировать SBOM через Syft (CycloneDX JSON)
      - name: Generate SBOM with Syft (CycloneDX JSON)
        run: |
          syft dir:. --output cyclonedx-json > sbom.json

      # 5) Залить SBOM как artifact
      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-json
          path: sbom.json

      # 6) Прогнать Trivy по SBOM
      - name: Scan SBOM with Trivy
        run: |
          trivy sbom sbom.json --format json --output trivy-report.json

      # 7) Залить отчет Trivy как artifact
      - name: Upload Trivy JSON report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: trivy-report.json
