# .github/workflows/sbom-cve.yml
name: SBOM & CVE Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  sbom-scan:
    name: Generate SBOM and scan for vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # ──────────────── Syft (SBOM) ────────────────
      - name: Install Syft v0.80.0
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin v0.80.0

      - name: Generate SBOM with Syft
        run: |
          syft . -o cyclonedx-json=sbom.json

      # ──────────────── Grype Scan ────────────────
      - name: Install Grype v0.78.0
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh \
            | sh -s -- -b /usr/local/bin v0.78.0

      - name: Run Grype vulnerability scan
        run: |
          grype sbom:sbom.json --fail-on medium

      # ──────────────── Trivy Scan ────────────────
      - name: Install Trivy via GitHub Action
        # ← здесь заменили на @v0.30.0, потому что v0.34.1 отсутствует
        uses: aquasecurity/trivy-action@v0.30.0

      - name: Run Trivy CVE scan
        run: |
          trivy sbom.json --severity HIGH,CRITICAL
