name: SBOM & CVE Scan

# Запускать при пуше и PR в ветку main
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  generate-sbom-and-scan:
    name: Generate SBOM and scan for vulnerabilities
    runs-on: ubuntu-latest

    steps:
      # 1) Проверяем код
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Устанавливаем Trivy, если не найден
      - name: Ensure Trivy is installed
        run: |
          if ! command -v trivy &> /dev/null; then
            echo "Installing Trivy v0.61.1..."
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
              | sudo bash -s -- -b /usr/local/bin v0.61.1
          fi

      # 3) Устанавливаем Syft, если не найден (для генерации SBOM)
      - name: Ensure Syft is installed
        run: |
          if ! command -v syft &> /dev/null; then
            echo "Installing Syft v0.84.0..."
            curl -sfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
              | sh -s -- -b /usr/local/bin v0.84.0
          fi

      # 4) Генерируем SBOM в формате CycloneDX JSON
      - name: Generate SBOM (CycloneDX JSON)
        run: |
          syft dir:. --output cyclonedx-json > sbom.json

      # 5) Заливаем сам SBOM как артефакт
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom-json
          path: sbom.json

      # 6) Сканируем SBOM через Trivy, сохраняем отчёт в JSON
      - name: Scan SBOM with Trivy
        run: |
          trivy sbom sbom.json --format json --output trivy-sbom-report.json

      # 7) Заливаем результат сканирования SBOM
      - name: Upload Trivy SBOM report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-sbom-report
          path: trivy-sbom-report.json
