# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025 Zilant Prime Core contributors

name: Static Analysis

on:
  pull_request:
    paths:
      - 'src/**/*.py'

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/python
          generateSarif: true
          sarifFile: semgrep.sarif          # ← имя файла задаём явно

      - name: Upload SARIF to CodeQL
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
