# .github/workflows/static-analysis.yml
name: Static Analysis — CodeQL & Semgrep

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  codeql-and-semgrep:
    name: CodeQL & Semgrep Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
          # Можно указать дополнительные queries, если нужно
          queries: security-and-quality

      - name: Autobuild (если есть компиляция, иначе пропустить)
        run: |
          echo "No-build step needed for pure-Python project"

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v2

      - name: Set up Node.js for Semgrep
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep --config p/ci
