# .github/workflows/static-analysis.yml
name: Static Analysis — Semgrep CI

on:
  push:
    branches:
      - main
      - ci-check-ready
  pull_request:
    branches:
      - main
      - ci-check-ready

jobs:
  semgrep:
    name: Semgrep SAST
    runs-on: ubuntu-latest
    steps:
      # 1. Забираем код
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Устанавливаем Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # 3. Устанавливаем dev-dependencies (включая semgrep)
      - name: Install dev dependencies
        run: pip install -e .[dev]

      # 4. Запускаем semgrep в режиме CI
      - name: Run Semgrep CI
        run: semgrep ci
