name: Static Analysis — CodeQL & Semgrep

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  codeql:
    name: CodeQL (python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: python
      - uses: github/codeql-action/analyze@v3

  semgrep:
    name: Semgrep scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep (CI rules)
        # --sarif сразу генерит отчёт, "|| true" гарантирует 0‑exit,
        # чтобы падал только при настоящих ошибках pipeline
        run: |
          semgrep scan --config p/ci --sarif --output semgrep.sarif || true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
