# .github/workflows/trivy-critical-scan.yml
name: Trivy Critical Vulnerability Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    name: Run Trivy Critical Scan on SBOM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ─────────────── Generate SBOM ───────────────
      - name: Install Syft v0.80.0
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin v0.80.0

      - name: Generate SBOM with Syft
        run: |
          syft . -o cyclonedx-json=sbom.json

      # ─────────────── Trivy Scan via Action ───────────────
      - name: Use Trivy Action to scan SBOM
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: sbom
          scan-ref: sbom.json
          severity: HIGH,CRITICAL

      # ──────────── (Опционально) Docker Image Scan ───────────
      # Если у вас есть Dockerfile и вы хотите одновременно проверять контейнер-образ, можно раскомментировать:
      #
      # - name: Build Docker image
      #   run: |
      #     docker build -t zilant-prime-app:latest .
      #
      # - name: Use Trivy Action to scan Docker image
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     scan-type: image
      #     image-ref: zilant-prime-app:latest
      #     severity: HIGH,CRITICAL
