# .github/workflows/trivy-critical-scan.yml

name: "Trivy Critical Vulnerability Scan on source tree"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-critical-scan:
    name: Run Trivy Critical Scan on source
    runs-on: ubuntu-latest

    steps:
      # ────────────────────────────────────────────────────────────────
      - name: 🔄 Checkout repository
        uses: actions/checkout@v4

      # ────────────────────────────────────────────────────────────────
      - name: 🛠 Install Trivy (v0.45.0 – совместимый)
        run: |
          # Скачиваем и ставим Trivy v0.45.0
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sh -s -- -b /usr/local/bin v0.45.0

      # ────────────────────────────────────────────────────────────────
      - name: 🔍 Run Trivy Critical Scan on full source tree
        run: |
          # Запускаем Trivy в режиме full filesystem scan (по-умолчанию CVE + License)
          trivy fs . --format json --output trivy-full-report.json --severity CRITICAL,HIGH

      # ────────────────────────────────────────────────────────────────
      - name: 📤 Upload Trivy full source scan report (JSON)
        uses: actions/upload-artifact@v4
        with:
          name: trivy-full-report
          path: trivy-full-report.json
