# .github/workflows/trivy-critical-scan.yml
name: Trivy Critical Vulnerability Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    name: Run Trivy (Image or SBOM)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ─────────────── Install Trivy ───────────────
      - name: Install Trivy via GitHub Action
        # ↓ тоже @master
        uses: aquasecurity/trivy-action@master

      # ──────────── Генерация SBOM (если её ещё нет) ────────────
      - name: Install Syft v0.80.0
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin v0.80.0

      - name: Generate SBOM with Syft
        run: |
          syft . -o cyclonedx-json=sbom.json

      # ──────────────── Запуск Trivy ────────────────
      - name: Run Trivy CVE scan on sbom.json
        run: |
          trivy sbom.json --severity HIGH,CRITICAL

      # Альтернатива: сканировать Docker-образ
      # - name: Build Docker image
      #   run: |
      #     docker build -t zilant-prime-app:latest .
      #
      # - name: Run Trivy image scan
      #   run: |
      #     trivy image --severity HIGH,CRITICAL zilant-prime-app:latest
