# .github/workflows/trivy-critical-scan.yml
name: Trivy Critical Vulnerability Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-sbom-scan:
    name: Run Trivy Critical Scan on SBOM
    runs-on: ubuntu-latest

    steps:
      # 1) Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Устанавливаем Trivy в среду
      - name: Install Trivy via Action
        uses: aquasecurity/trivy-action@master

      # 3) Генерируем SBOM (CycloneDX-JSON) с помощью Trivy
      - name: Generate SBOM (CycloneDX-JSON) with Trivy
        run: |
          trivy sbom --format cyclonedx --output sbom.json .

      # 4) Сканируем SBOM на уязвимости HIGH/CRITICAL
      - name: Scan SBOM for HIGH/CRITICAL vulnerabilities
        run: |
          trivy sbom --format table --scanners vuln --severity HIGH,CRITICAL sbom.json

      # 5) Опционально: Можно зааплоадить sbom.json и отчёт
      - name: Upload sbom.json artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom-json
          path: sbom.json

      - name: Save Trivy report
        if: always()
        run: |
          trivy sbom --format json --scanners vuln --severity HIGH,CRITICAL sbom.json > trivy-report.json
      - name: Upload JSON report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: trivy-sbom-report
          path: trivy-report.json
