name: Trivy Critical Vulnerability Scan

# Запускать при пуше и PR в ветку main
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-critical-scan:
    name: Run Trivy Critical Scan on source tree
    runs-on: ubuntu-latest

    steps:
      # 1) Проверяем код
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Устанавливаем Trivy, если не найден
      - name: Ensure Trivy is installed
        run: |
          if ! command -v trivy &> /dev/null; then
            echo "Installing Trivy v0.61.1..."
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
              | sudo bash -s -- -b /usr/local/bin v0.61.1
          fi

      # 3) Запускаем Trivy-файловый скан (Filesystem scan) и выбираем только severity=CRITICAL
      - name: Run Trivy filesystem scan (Critical only)
        run: |
          # Пишем результат в trivy-critical.json
          trivy fs . --severity CRITICAL --format json --output trivy-critical.json

      # 4) Заливаем JSON-отчёт Trivy с результатами
      - name: Upload Trivy critical report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-critical-report
          path: trivy-critical.json
