# .github/workflows/trivy-critical-scan.yml
name: Trivy Critical Vulnerability Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    name: Run Trivy (Image or SBOM)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker (если сканируете образ)
        uses: docker/setup-buildx-action@v2

      - name: Pull latest base image (опционально)
        run: |
          docker pull python:3.13-slim

      # ───────────── Если хотите сканировать контейнерную сборку ─────────────
      # - name: Build Docker image
      #   run: |
      #     docker build -t my-app:latest .

      # - name: Run Trivy scan against Docker image
      #   run: |
      #     trivy image --severity HIGH,CRITICAL my-app:latest

      # ───────────── Если хотите сканировать SBOM ─────────────
      - name: Install Trivy
        uses: aquasecurity/trivy-action@v0.10.1

      - name: Run Trivy CVE scan on sbom.json
        run: |
          # Генерация sbom.json должна быть в sbom-cve.yml, но тут можно повторить:
          syft . -o cyclonedx-json=sbom.json
          trivy sbom.json --severity HIGH,CRITICAL
