# SPDX-FileCopyrightText: 2025 Zilant Prime Core contributors
# SPDX-License-Identifier: MIT
name: Trivy Critical Vulnerability Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    name: SBOM & Trivy/Grype Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Syft (SBOM generation)
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM in CycloneDX JSON
        run: |
          set -e
          syft . -o cyclonedx-json=sbom.json

      - name: Upload SBOM artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: sbom-json
          path: sbom.json

      - name: Install Grype for SBOM scan
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Grype scan against SBOM (fail on ≥ MEDIUM)
        run: |
          set -e
          grype sbom:sbom.json --fail-on medium

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.45.0

      - name: Run Trivy filesystem scan (CRITICAL,HIGH)
        run: |
          set -e
          trivy fs --exit-code 1 --severity CRITICAL,HIGH --format json --output trivy-report.json .

      - name: Upload Trivy report (JSON)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
