# .github/workflows/trivy-critical-scan.yml
name: Trivy Critical Vulnerability Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    name: Run Trivy (Image or SBOM)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Пример: сканировать SBOM (если хотите отдельно от sbom-cve.yml)
      - name: Install Trivy via GitHub Action
        uses: aquasecurity/trivy-action@v0.34.1

      - name: Generate SBOM with Syft (если его нет)
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin v0.80.0
          syft . -o cyclonedx-json=sbom.json

      - name: Run Trivy CVE scan on sbom.json
        run: |
          trivy sbom.json --severity HIGH,CRITICAL

      # Альтернативный вариант: сканировать Docker-образ
      # - name: Build Docker image
      #   run: |
      #     docker build -t zilant-prime-app:latest .
      #
      # - name: Run Trivy scan against Docker image
      #   run: |
      #     trivy image --severity HIGH,CRITICAL zilant-prime-app:latest
