# .github/workflows/trivy-critical-scan.yml
name: Trivy Critical Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sbom_critical_scan:
    name: Generate & Scan SBOM → Trivy (CRITICAL)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sh -s -- -b /usr/local/bin

      - name: Generate CycloneDX SBOM with Trivy
        run: trivy sbom --format cyclonedx --output sbom.json .

      - name: Scan SBOM for CRITICAL vulnerabilities
        run: trivy sbom sbom.json --exit-code 1 --severity CRITICAL

  fs_critical_scan:
    name: Scan FS → Trivy (CRITICAL)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sh -s -- -b /usr/local/bin

      - name: Scan filesystem for CRITICAL vulnerabilities
        run: trivy fs --exit-code 1 --severity CRITICAL .
