name: Build UI
on:
  push:
    paths: ["ui/**", ".github/workflows/ui-build.yml"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: |
          pip install pyinstaller
          pyinstaller --onefile ui/main.py
      - uses: actions/upload-artifact@v4
        with:
          name: ui-dist
          path: dist/*
