name: Vault Secret Injection

on:
  workflow_dispatch:

jobs:
  vault:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch and Inject Vault Secrets
        uses: hashicorp/vault-action@v2.2.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/zilant  mysecret  VAULT_TOKEN
      - name: Use secret
        run: echo "Secret length: ${#VAULT_TOKEN}"
