# .github/workflows/vault-rotate-app-token.yml
name: Rotate Vault App Token

# Запускается по расписанию (каждые 8 часов)
on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  rotate-token:
    name: Rotate Vault App Token
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to HashiCorp Vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: token
          token: ${{ secrets.VAULT_TOKEN }}

      - name: Rotate application token in Vault
        run: |
          # Здесь ваш конкретный скрипт/аналог curl-запроса для ротации токена
          # Например:
          # curl --header "X-Vault-Token: ${{ secrets.VAULT_TOKEN }}" \
          #      --request POST \
          #      --data '{"policies":["app-policy"],"ttl":"1h"}' \
          #      https://vault.example.com/v1/auth/token/create
          echo "Rotation logic goes here"
