name: zilant-ci

on:
  push:
    branches:
      - main
      - ci-check-ready
  pull_request:
    branches:
      - main
      - ci-check-ready

jobs:
  quality:
    name: quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dev dependencies
        run: pip install -e .[dev]

      - name: Pre-commit hooks
        run: pre-commit run --all-files

      - name: Ruff
        run: ruff check .

      - name: Black
        run: black --check .

      - name: isort
        run: isort --check-only .

      - name: Bandit
        run: bandit -r src -ll

      - name: Semgrep CI
        run: semgrep ci

      - name: Mypy
        run: mypy --config-file mypy.ini src

      - name: Pytest
        run: pytest -q

  perf:
    name: perf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - run: pip install -e .[dev]
      - run: pytest -q --maxfail=1 --disable-warnings -m perf

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Build PQ wheels
        run: python tools/build_pq_wheels.py

      - name: Upload PQ wheels
        uses: actions/upload-artifact@v4
        with:
          name: pq-wheels
          path: dist/*.whl

      - name: Install Pandoc & XeLaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex fonts-dejavu

      - name: Generate Whitepaper
        run: |
          pandoc \
            docs/whitepaper.md \
            docs/ARCH.md \
            docs/THREATS.md \
            --metadata-file docs/whitepaper.yml \
            -o dist/whitepaper.pdf \
            --pdf-engine=xelatex \
            -V mainfont="DejaVu Serif" \
            -V monofont="DejaVu Sans Mono"

      - name: Upload Whitepaper
        uses: actions/upload-artifact@v4
        with:
          name: whitepaper
          path: dist/whitepaper.pdf

  sign:
    name: sign
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - run: pip install -e .[dev]
      - run: python tools/sign_artifacts.py
      - uses: actions/upload-artifact@v4
        with:
          name: signed-artifacts
          path: signed/*
